# Generated by Django 2.1.7 on 2019-04-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundationVM',
            fields=[
                ('ip_address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
