# Generated by Django 2.1.7 on 2019-04-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190403_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='creation_time',
        ),
    ]
