# Generated by Django 2.1.7 on 2019-04-01 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='asset',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
        ),
    ]
