# Generated by Django 2.1.7 on 2019-05-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_auto_20190401_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
